steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '--build-arg', 'API_BASE_URL=https://fastapi-app-390550640662.us-central1.run.app',
        '-t', 'us-central1-docker.pkg.dev/hackathon-472304/frontend-repo/streamlit-frontend:latest',
        '.'
      ]
images:
  - 'us-central1-docker.pkg.dev/hackathon-472304/frontend-repo/streamlit-frontend:latest'
