steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '--build-arg', 'NEXT_PUBLIC_API_BASE_URL=https://fastapi-app-390550640662.us-central1.run.app',
        '--build-arg', 'GEMINI_API_KEY=AIzaSyCG_RaIGoBFlAMH89c_97LUpvVGOlbiO-w',
        '-t', 'us-central1-docker.pkg.dev/hackathon-472304/frontend-repo/nextjs-frontend:latest',
        '.'
      ]
images:
  - 'us-central1-docker.pkg.dev/hackathon-472304/frontend-repo/nextjs-frontend:latest'
